Status Checked

diff --git a/.github/workflows/status-check.yml b/.github/workflows/status-check.yml
--- a/.github/workflows/status-check.yml
+++ b/.github/workflows/status-check.yml
@@ -8,9 +8,15 @@ jobs:
             - name: Step1
               run: sleep 20
 
+            - name: Step2
+              id: step-2
+              run: exit 1
+
             - name: Runs on failure
-              if: failure()
-              run: echo 'Runs on failure'
+              #if: failure()
+              if: steps.step-2.conclusion == 'failure'
+              #run: echo 'Runs on failure'
+              run: "Step2 has failed"
 
               #Below not needed as it's the default behavior
             - name: Runs on success
